### ISSUE TITLE
[New Plug-in] Git

### ISSUE THREAD

**Issue by x80486** [asdf-vm/asdf-plugins#120]
Actually, I don't know if it's possible to have `Git` as an `asdf` plugin, but I'm just filing this one just in case :sunglasses:

**Comment by Stratus3D** [comment]
I'm not actually sure if this would work or not. Git is a dependency of asdf, so it must be installed prior to asdf. Although I don't see any reason why asdf could not manage additional versions of Git if a plugin were created for it. A Git plugin may uncover some edge cases in asdf though.

For users, I'm not sure how a Git plugin would be useful. They have to manually install one version of Git anyway, and I'm not sure how many people need to run different versions of Git at the same time. @x80486 do you have a need for multiple Git versions?

**Comment by x80486** [comment]
No, I don't actually need several `Git` versions. I was more thinking about a traditional package manager (because I'm in my quest to be able to uninstall `Nix`), but I didn't realize about the dependency :sweat_smile:, so it can become somehow confusing.

We can close this one :+1:
