### ISSUE TITLE
README improvements

### ISSUE THREAD

**Issue by Stratus3D** [asdf-vm/asdf-plugins#25]
A link to the plugin guide needs to be displayed in the section of the readme that covers adding plugins.

We also need to specify the standards for plugin inclusion. Plugins without automated test builds are not included, nor are those with failing builds.

We also need to say that any plugin that is added can be removed or replaced at any time for any reason. There are two reasons this may be necessary:

* It's quite probably we will have multiple plugins for the same programming language. One will likely be better maintained than the other.
* There could be a plugin containing malicious code.

**Comment by vic** [comment]
Added some comments, feel free to edit or reword.

**Comment by Stratus3D** [comment]
Thanks @vic. That's perfect. I added one point about the file in `plugins/`.
