### ISSUE TITLE
Fix R

### ISSUE THREAD

**Issue by n8sty** [asdf-vm/asdf-plugins#274]
The R plugin is not currently being maintained. The plugin is working well enough but see https://github.com/iroddis/asdf-R/issues/8 and https://github.com/iroddis/asdf-R/pull/6 for evidence of the plugin's lack of maintenance. I'm happy to maintain this for the foreseeable future, opening a PR to that effect.

**Comment by smorimoto** [comment]
@n8sty @taiar @iroddis #275 and #273 seem to be duplicated. I can't decide which to merge. Are you willing to move it to the asdf-community and do maintenance?

**Comment by taiar** [comment]
@smorimoto yes, sure, it will be a pleasure to help

**Comment by n8sty** [comment]
@smorimoto I'm in!

**Comment by jthegedus** [comment]
Please continue the discussion of merging this plugin into asdf-community. Just merged to get an updated R plugin into the repo in the meantime.

**Comment by taiar** [comment]
I was looking at this issue, so, for following up: what I have to do to move this plugin to the asdf-community?

**Comment by jthegedus** [comment]
@taiar I think this is the repo to look at https://github.com/asdf-community/.github

**Comment by taiar** [comment]
Thanks @jthegedus, I will open a new issue there.

**Comment by jthegedus** [comment]
closed in #442
