### ISSUE TITLE
Case sensitivity

### ISSUE THREAD

**Issue by cehoffman** [asdf-vm/asdf-plugins#28]
The naming of plugins has a bad inconsistency between platforms due to case sensitivity of the filesystem.

On OS X `asdf plugin-add luajit` works, but on a standard linux install `asdf plugin-add luaJIT` is requried. I suggest that plugins should all be a single case for consistency between platforms. Since the vast majority of the plugins are currently in lowercase, this should be the default and requirement of future plugins.

**Comment by adamu** [comment]
When I install Elixir, for example, using `asdf install elixir 1.6.5`, it installs it as capital-E `Elixir` (visible via `asdf list`).

If I then do `asdf global elixir 1.6.5`, the command succeeds and adds a lower-e `elixir` entry to `.tool-versions`, but it is ignored by `asdf global`. It's necessary to use the upper-case version: `asdf global Elixir 1.6.5`.

**Comment by Stratus3D** [comment]
I'm open to suggestions how we should deal with case sensitivity. @adamu you are correct, the argument you give to `asdf plugin-add` becomes the directory name, and all later commands must match that directory name exactly.

**Comment by jthegedus** [comment]
I support a change to forcing lowercase.

**Comment by hyperupcall** [comment]
I think this can now be closed - `asdf-vm/asdf` now validates for proper casing when adding/removing plugins
