### ISSUE TITLE
Maintainership help?

### ISSUE THREAD

**Issue by ghostsquad** [asdf-vm/asdf-plugins#347]
I love ASDF, and would like to contribute more, and possibly be a maintainer. It seems there are PRs piling up that could use merging, and direction to resolution.

Can I help?

**Comment by jthegedus** [comment]
It is a slow time of year for OSS, I know my time to invest to asdf solution will increase in the next week as the holiday period ends.

Feel free to contribute directly to the discussions you believe are stagnant. I am not opposed to "ping" comments, but direct suggestions or cotnributions to the discussions are more welcome.

I have some WIP ideas to remove the toil this repo generates but it involves changes to the core `asdf` also (I hope to get this in a PR very soon and get discussion the solution to more users/maintainers eyes).

More eyes on PRs is always helpful, even if not from existing 'maintainers'.

**Comment by jthegedus** [comment]
I think we're on top of the PRs as of now.

As for the remaining issues, the "plugin request" types are straightforward and the others I see as being solved by my previous comment.

I think "Case sensitivity" is the only issue not addressed by this and my prior comments.

Going to close this for now. Feel free to reopen should you see this as an issue again :pray:
