### ISSUE TITLE
[New Plug-in]: azure-cli

### ISSUE THREAD

**Issue by luizfelipefb** [asdf-vm/asdf-plugins#359]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add the [azure-cli](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli) plugin

**Describe similar asdf features and why they are not sufficient**
We already have gcloud and aws but we could also have azure

**Describe workarounds you've considered**
Manually install azure-cli in the machine

**Additional context**
N/A

**Comment by jthegedus** [comment]
I would encourage anyone who tackles this to use existing packaged CLI instead of building from source as it requires fewer dependencies for users.

Additionally, is anyone able to share source URLs for said packages here for whomever tackles this?

**Comment by luizfelipefb** [comment]
> I would encourage anyone who tackles this to use existing packaged CLI instead of building from source as it requires fewer dependencies for users.

That's what I did

> Additionally, is anyone able to share source URLs for said packages here for whomever tackles this?

https://github.com/Azure/azure-cli

**Comment by jthegedus** [comment]
I meant more like https://aka.ms/InstallAzureCli

**Comment by itspngu** [comment]
I didn't realize there was an issue for this, I wrote a plugin: https://github.com/asdf-vm/asdf-plugins/pull/547

Perhaps useful as a reference for similar future plugins: In short, I [list versions](https://github.com/itspngu/asdf-azure-cli/blob/f42374ba3e46502fc05d0d6fab30b8ef6609079b/bin/list-all#L12) and [download](https://github.com/itspngu/asdf-azure-cli/blob/master/bin/download#L10) the `.whl` file from PyPi, [install](https://github.com/itspngu/asdf-azure-cli/blob/f42374ba3e46502fc05d0d6fab30b8ef6609079b/bin/install#L21) it into a `venv` using pip, and then [dump a short wrapper script](https://github.com/itspngu/asdf-azure-cli/blob/f42374ba3e46502fc05d0d6fab30b8ef6609079b/bin/install#L23) for invoking it.

The last part is inspired by what the official installer script does. Works like a charm.

**Comment by jthegedus** [comment]
closed in #547
