### ISSUE TITLE
Listed jq plugin is unstable and unmaintained

### ISSUE THREAD

**Issue by wren** [asdf-vm/asdf-plugins#419]
**Describe the bug**
I'm not sure if this is the right place to report this, but the listed `jq` plugin (https://github.com/focused-labs/asdf-jq) is unstable and seems not to be maintained anymore (open issues and PRs with no response, no commits for over a year, etc).

There's a fork mentioned in an issue there (focused-labs/asdf-jq#6) that looks to have more activity and is more stable (https://github.com/AZMCode/asdf-jq). It's not my fork, but I wanted to point out that I had lots of trouble installing with the default plugin, and @AZMCode 's fork worked perfectly first try.

**Comment by AZMCode** [comment]
Let me drop in to say that, if my fork of the plugin is listed, I'm committed to maintaining it.

**Comment by jthegedus** [comment]
Happy to get a PR to update the `jq` in this repo.

**Comment by AZMCode** [comment]
In a bit

**Comment by wren** [comment]
@jthegedus @AZMCode PR sent.

**Comment by AZMCode** [comment]
Thank you. Sorry for the delay 😅

**Comment by wren** [comment]
@AZMCode There's nothing to be sorry for. Your fork saved me a lot of time the other day, so I figured a quick PR is the least I could do to maybe return the favor.

**Comment by jthegedus** [comment]
Thanks to you both :)
