### ISSUE TITLE
[New Plugin]: Kubevela

### ISSUE THREAD

**Issue by josephlim75** [asdf-vm/asdf-plugins#539]
### Is your feature request related to a problem? Please describe

It is not a problem.  I just wanted to share the plugin I have created for `kubevela'  https://kubevela.io

### Describe the proposed solution

The plugin is located at 
https://github.com/josephlim75/asdf-kubevela.git

### Describe similar `asdf` features and why they are not sufficient

none

### Describe other workarounds you've considered

none

**Comment by jthegedus** [comment]
Please submit a PR. You can look at previously merged PRs to see what is required, it should only be 2 lines of code to submit your tool. Thanks for making a plugin!

**Comment by pdemagny** [comment]
Hi,
Both the vela and velad cli tools of the kubevela project are now part of the official plugins following the 2 PRs I submitted recently and that were accepted. I made those two plugins with the official plugins templates, and got approval from the official project maintainers, see #709 & #710.
For this reason I think this issue can be closed.

**Comment by jthegedus** [comment]
Thanks @pdemagny 

@josephlim75 you can continue to use, improve and maintain your plugin as people can still utilise it by installing the plugin directly `asdf plugin-add kubevela https://github.com/josephlim75/asdf-kubevela.git`
