### ISSUE TITLE
[New Plugin]: sccache

### ISSUE THREAD

**Issue by emersonmx** [asdf-vm/asdf-plugins#559]
### Is your feature request related to a problem? Please describe

It is not a problem. I just wanted to share the plugin I have created for `sccache' https://github.com/mozilla/sccache

### Describe the proposed solution

The plugin is located at https://github.com/emersonmx/asdf-sccache.git

### Describe similar `asdf` features and why they are not sufficient

none

### Describe other workarounds you've considered

none

**Comment by jthegedus** [comment]
Please submit a PR. You can look at previously merged PRs to see what is required, it should only be 2 lines of code to submit your tool. Thanks for making a plugin!
