### ISSUE TITLE
[New Plugin]: Stoplight Spectral CLI

### ISSUE THREAD

**Issue by vbyrd** [asdf-vm/asdf-plugins#645]
### Is your feature request related to a problem? Please describe

asdf does not have a spectral plugin

### Describe the proposed solution

I have created a spectral plugin for asdf. I've created a PR (https://github.com/asdf-vm/asdf-plugins/pull/644) to add it to this list.
[vbyrd/asdf-spectral](https://github.com/vbyrd/asdf-spectral)
[![Build Status](https://github.com/vbyrd/asdf-spectral/workflows/Build/badge.svg)](https://github.com/vbyrd/asdf-spectral/actions)

### Describe similar `asdf` features and why they are not sufficient

N/A

### Describe other workarounds you've considered

N/A

**Comment by jthegedus** [comment]
Resolved in #644
