### ISSUE TITLE
Remove asdf-conduit plugin

### ISSUE THREAD

**Issue by marcwrobel** [asdf-vm/asdf-plugins#668]
### Is your feature request related to a problem? Please describe

The [asdf-conduit](https://github.com/gmcabrita/asdf-conduit) repository has been archived by its author, @gmcabrita. So it is safe to assume that this plugin is not maintained anymore.

### Describe the proposed solution

This plugin should be removed from the asdf-plugins repository.

### Describe similar `asdf` features and why they are not sufficient

N/A

### Describe other workarounds you've considered

This plugin could also be transferred to asdf-community.

**Comment by jthegedus** [comment]
If it is no longer working, I think the best course is to remove it from the plugin list, it can be added again later once it is migrated owners or not.

**Comment by marcwrobel** [comment]
@jthegedus, I do not know if it's working or not. I am only sure it's not maintained anymore. That intention was made explicit when @gmcabrita archived the repository.

I think it's best to remove it for the time being from the plugin list. What do you think ?

**Comment by jthegedus** [comment]
Code not working and the repo being archived are two separate things.

**Comment by marcwrobel** [comment]
Closing the issue, quoting https://github.com/asdf-vm/asdf-plugins/issues/670#issuecomment-1238785230 :
> If it is working then we should leave it here even if the repo is archived. The fact it is archived doesn't stop people using it nor does it imply it is not working. If it stops working at some point then we can remove it and add a new replacement repo once someone makes a replacement.
