### ISSUE TITLE
Remove asdf-stack plugin

### ISSUE THREAD

**Issue by marcwrobel** [asdf-vm/asdf-plugins#671]
### Is your feature request related to a problem? Please describe

The [asdf-stack](https://github.com/sestrella/asdf-stack) repository has been archived by its author, @sestrella. So it is safe to assume that this plugin is not maintained anymore.

### Describe the proposed solution

This plugin should be removed from the asdf-plugins repository.

### Describe similar `asdf` features and why they are not sufficient

N/A

### Describe other workarounds you've considered

This plugin could also be transferred to asdf-community.

**Comment by sestrella** [comment]
@marcwrobel thank you for looping me in, I already have a [replacement](https://github.com/sestrella/asdf-ghcup) for this plugin, so I'm going to submit a PR updating the repository URL
