### ISSUE TITLE
[New plugin] Raku

### ISSUE THREAD

**Issue by noraj** [asdf-vm/asdf-plugins#687]
### Is your feature request related to a problem? Please describe

No problem

### Describe the proposed solution

Raku is a language that was meant to be Perl 6 at first. https://raku.org/
The official compiler is Rakudo https://rakudo.org/

### Describe similar `asdf` features and why they are not sufficient

There is no plugin for this language

### Describe other workarounds you've considered

Rakudo is already provided in official repositories of many linux distribution : fedora, ubuntu, debian, opensuse, alpine, gentoo, nixos, but not on ArchLinux so I'll have to use a user repository or a standalone binary

**Comment by m-dango** [comment]
In development: https://github.com/m-dango/asdf-raku
