### ISSUE TITLE
Change default sbt plugin

### ISSUE THREAD

**Issue by sciamp** [asdf-vm/asdf-plugins#70]
Current default sbt plugin is using [bin tray](https://dl.bintray.com/sbt/native-packages/sbt/) that is somehow stuck in the past (at release 1.0.0-M4, while current sbt release is 1.2.8)

I'm using [this other plugin](https://github.com/gabrielelana/asdf-sbt) that uses [GitHub API](https://developer.github.com/v3/repos/#list-tags) to retrieve sbt releases.

I'm making a PR for this.

Thanks

**Comment by Stratus3D** [comment]
Thanks for reporting. I ended up merging an existing PR for this - https://github.com/asdf-vm/asdf-plugins/pull/53
