### ISSUE TITLE
[New Plugin]: AWS Amplify CLI

### ISSUE THREAD

**Issue by LozanoMatheus** [asdf-vm/asdf-plugins#767]
### Is your feature request related to a problem? Please describe

Add the [AWS Amplify CLI](https://docs.amplify.aws/cli/) plugin

### Describe the proposed solution

I create a PR #766 that adds the plugin

### Describe similar `asdf` features and why they are not sufficient

It's missing this plugin

### Describe other workarounds you've considered

None

**Comment by jthegedus** [comment]
closed in #766
