### ISSUE TITLE
It seems that the plugin `asdf-community/asdf-python` has their issues accumulated without people responsible for it?

### ISSUE THREAD

**Issue by nyngwang** [asdf-vm/asdf-plugins#782]
### Describe the Bug

As title. The project is still listed in [README.md](https://github.com/asdf-vm/asdf-plugins#plugin-list), but it seems that issues there are accumulating(e.g. some [year-old](https://github.com/asdf-community/asdf-python/issues/123) issues) without any reply by the maintainers.

### Steps to Reproduce

0.

### Expected Behaviour

as above

### Actual Behaviour

as above

### Environment

```shell
as above
```

**Comment by jthegedus** [comment]
I cannot speak to maintainers of other projects. `asdf-python` was created by one of the asdf core team members and then migrated to the community repos. The `asdf-community` is not owned or maintained by the asdf core team. Some members may have contributed to both in the past, but it is not part of the asdf core so therefore not much else we can do about it.

**Comment by jthegedus** [comment]
I am not sure of the exact users under the `asdf-community` organisation within GitHub, but I suggest finding who that group of people are and then tag them in the repo.
