### ISSUE TITLE
Java plugin no longer able to install modern JDKs.

### ISSUE THREAD

**Issue by halcyon** [asdf-vm/asdf-plugins#79]
Oracle has blocked unauthenticated downloads of modern builds of the JDK. They still provide unauthenticated access to some builds of JDK 8 and 7 that are a few years old, but this leaves users of more modern builds of JDK 8, 9, 10, 11 and 12 without an asdf option. The issue has been solved with an updated java plugin in PR #78 .

**Comment by canterberry** [comment]
@halcyon This seems like an issue with the Java plugin (vs the asdf-plugins repo itself). Also, are you still experiencing the issue? It's been working fine for me lately, so I think #78 did the trick.

**Comment by Stratus3D** [comment]
Looks like #78 solved this. Closing.
