### ISSUE TITLE
Swift plugin was removed from the README.md

### ISSUE THREAD

**Issue by susurri** [asdf-vm/asdf-plugins#827]
### Describe the Bug

https://github.com/asdf-vm/asdf-plugins/pull/39 removed swift plugin from the README.md, which must be an accident.

### Steps to Reproduce

see the README.md

### Expected Behaviour

swift plugin IS in the README.md

### Actual Behaviour

swift plugin is NOT in the README.md

### Environment

```shell
none
```

**Comment by jthegedus** [comment]
This may have been removed by mistake.

These plugins are community driven, so if you wish to see a plugin here, then please PR an update.
