### ISSUE TITLE
`asdf-community` GH Discussions doesn't work

### ISSUE THREAD

**Issue by andreaTP** [asdf-vm/asdf-plugins#850]
### Describe the Bug

Hi all and thanks for the excellent project, I have been attempting to submit a new plugin to `asdf-community` by reaching out by email as explained [here](https://github.com/asdf-community#how-do-i-move-plugins-here).

I haven't received any response in > 1 month and have noticed things moving much faster through GH Discussions.
Unfortunately, it seems to be impossible to open new Discussions under the `asdf-community` organization.
![Screenshot 2023-06-29 at 16 08 35](https://github.com/asdf-vm/asdf-plugins/assets/5792097/34a0be6e-6757-4277-8ae8-54d60997e866)

I hope this is the right place to reach out to @smorimoto or @vic 🙏  and sorry for the noise if this is not the right channel.

**Comment by smorimoto** [comment]
Sorry. I've been pretty busy over the past year and more and more people have sent me emails and when I invite them many maintainers don't transfer repositories and as a result I just waste Terraform-related work. It’s true that this has caused me to be a bit backwards and some communications have been delayed and I’m sorry but I think I can take care of your request soon.

**Comment by andreaTP** [comment]
No big worries and no rush, I was just trying an alternative communication channel since I haven't received feedback 🙂

**Comment by smorimoto** [comment]
Weirdly, I get that error as well...

**Comment by jthegedus** [comment]
@andreaTP Please close when you feel your problem has been resolved.

**Comment by smorimoto** [comment]
Fixed now!

**Comment by andreaTP** [comment]
Confirm, now it works: https://github.com/orgs/asdf-community/discussions/57
Thanks @smorimoto !
