### ISSUE TITLE
[NEW PLUGIN] eza

### ISSUE THREAD

**Issue by lwiechec** [asdf-vm/asdf-plugins#878]
### Is your feature request related to a problem? Please describe

none

### Describe the proposed solution

[eza](https://github.com/eza-community/eza) is a `ls`-like command, follower of since unmaintained [exa](https://github.com/ogham/exa)

### Describe similar `asdf` features and why they are not sufficient

[asdf-exa](https://github.com/nyrst/asdf-exa) exists; because `exa` is not maintained anymore and points to `eza`, it makes sens to create a plugin

### Describe other workarounds you've considered

none

**Comment by jthegedus** [comment]
Closed in #880
