### ISSUE TITLE
CI produce false red

### ISSUE THREAD

**Issue by kvokka** [asdf-vm/asdf-plugins#97]
While added PR https://github.com/asdf-vm/asdf-plugins/pull/96 I found, that CI gave me red status, while my plugin is working.

It happening because of coupling all plugins in 1 bunch, and if even 1 fails - test fails.

But we do not control the plugins after PR merge, so we can not base on this criteria. It can be only warning, and test script should test only new plugin, and be red only while it is red.

Any thoughts?

**Comment by Stratus3D** [comment]
I think this is closely related to #84. Closing this issue. Let's continue to the discussion on the other issue.
